#ifndef __DEF_H__
#define __DEF_H__

#define DEF_TEST_AREA_WIDTH  800
#define DEF_TEST_AREA_HEIGHT 600
#define DEF_TEST_AREA_RATIO  (DEF_TEST_AREA_WIDTH / (float)DEF_TEST_AREA_HEIGHT)

#define DEF_SEGMENT_MAX      5000000
#define DEF_SEGMENT_AMOUNT     25000
#define DEF_SEGMENT_VIEW_MAX ((3840 * 2160) / 5000)

#define DEF_INTERSECTION_VIEW_MAX ((DEF_SEGMENT_VIEW_MAX - 1) * DEF_SEGMENT_VIEW_MAX / 2)

_Static_assert(DEF_SEGMENT_MAX >= 2, "Two or more segments needed");

#define DEF_CELLS_PER_SEGMENT_ESTIMATE   40
#define DEF_CELLS_LINE_MAX              128
#define DEF_CELLS_COLUMN_MAX            128
#define DEF_CELLS_MAX (DEF_CELLS_LINE_MAX * DEF_CELLS_COLUMN_MAX)

#endif
