#ifndef __DEF_H__
#define __DEF_H__

#define DEF_SEGMENT_LENGTH_MAX 300

#define DEF_SEGMENT_MAX      5000000
#define DEF_SEGMENT_AMOUNT      5000
#define DEF_SEGMENT_VIEW_MAX   10000

#define DEF_INTERSECTION_VIEW_MAX ((DEF_SEGMENT_VIEW_MAX - 1) * DEF_SEGMENT_VIEW_MAX / 2)

_Static_assert(DEF_SEGMENT_MAX >= 2, "Two or more segments needed");

#define DEF_STATUS_BAR_LENGHT 1000
#define DEF_STATUS_BAR_HEIGHT   10

#define DEF_WINDOW_WIDTH  800
#define DEF_WINDOW_HEIGHT 600

#define DEF_CELLS_PER_SEGMENT_ESTIMATE  7
#define DEF_CELLS_LINE_MAX             30
#define DEF_CELLS_COLUMN_MAX           40
#define DEF_CELLS_MAX (DEF_CELLS_LINE_MAX * DEF_CELLS_COLUMN_MAX)

#define DEF_MAX_RAM_USAGE_ESTIMATE 6000000000

#endif
